services:
  licence_db:
    image: postgres:16
    container_name: licence_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - licence-network
    volumes:
      - licence_db_data:/var/lib/postgresql/data

  licence-pgadmin:
    image: dpage/pgadmin4
    container_name: licence-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - licence-network
    depends_on:
      - licence_db
    volumes:
      - licence-pgadmin_data:/var/lib/pgadmin

  licence-nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - licence-server
    networks:
      - licence-network
    restart: unless-stopped

  licence-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: licence-server
    volumes:
      - ./server:/var/www/html
    networks:
      - licence-network
    depends_on:
      - licence_db

  licence-migrator:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: licence-migrator
    command: sh -c "php artisan migrate"
    volumes:
      - ./server:/var/www/html
    networks:
      - licence-network
    depends_on:
      - licence-server
    restart: on-failure

volumes:
  licence_db_data:
  licence-pgadmin_data:

networks:
  licence-network:
    driver: bridge